# Generated by Django 5.0.2 on 2024-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projekt_faks'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='tags',
            field=models.ManyToManyField(to='projects.tag'),
        ),
    ]
