# Generated by Django 5.0.2 on 2024-04-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_predmet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='overview',
            field=models.TextField(default='aaaaa'),
        ),
    ]
