# Generated by Django 5.0.2 on 2024-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_predlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='email',
            field=models.TextField(default='nekaj@gmail.com'),
        ),
    ]
